{
 "title": "Admin-Dogu Dashboard",
 "description": "Admin-Dogu Dashboard",
 "tags": [
  "kubernetes",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(node)" } },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU-Nutzung aller Nodes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg (irate(node_cpu_seconds_total{mode=\"idle\",node=~\"^$Node$\",job=\"node-exporter\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Genutzte CPU-Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=~\"/.*\",node=~\"^$Node$\"}[2m]))"
    }
   ]
  },
  {
   "title": "Reservierte CPU-Cores",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{node=~\"^$Node$\",resource=\"cpu\"}) / sum (machine_cpu_cores{node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Angefragt (CPU-Cores)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{node=~\"^$Node$\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Gesamt (CPU-Cores)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "CPU-Nutzung je Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{image!=\"\",node=~\"^$Node$\", namespace=~\"^$namespace$\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Arbeitsspeicher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Arbeitsspeicher aller Nodes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1- ((avg_over_time(node_memory_MemFree_bytes{node=~\"^$Node$\", job=\"node-exporter\"}[5m]) + avg_over_time(node_memory_Cached_bytes{node=~\"^$Node$\", job=\"node-exporter\"}[10m]) + avg_over_time(node_memory_Buffers_bytes{node=~\"^$Node$\",job=\"node-exporter\"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{node=~\"^$Node$\",job=\"node-exporter\"}[5m])))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Genutzter Arbeitsspeicher",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=~\"/.*\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Reservierter Arbeitsspeicher",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{node=~\"^$Node$\",resource=\"memory\"}) / sum (machine_memory_bytes{node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Angefragt (Arbeitsspeicher)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{node=~\"^$Node$\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Gesamt (Arbeitsspeicher)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Arbeitsspeicher-Nutzung je Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\" ,namespace=~\"^$namespace$\",container!=\"POD\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Dateisystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Dateisystemnutzung aller Nodes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",node=~\"^$Node$\",job=\"node-exporter\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",node=~\"^$Node$\",job=\"node-exporter\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Genutztes Node-Dateisystem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",node=~\"^$Node$\",job=\"node-exporter\"} - node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",node=~\"^$Node$\",job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Dateisystemnutzung aller Volumes",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kubelet_volume_stats_used_bytes{service=\"k8s-prometheus-kubelet\"}) / sum (kubelet_volume_stats_capacity_bytes{service=\"k8s-prometheus-kubelet\"}) * 100"
    }
   ]
  },
  {
   "title": "Verwendet (Volume)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kubelet_volume_stats_used_bytes{service=\"k8s-prometheus-kubelet\"})"
    }
   ]
  },
  {
   "title": "Gesamt (Volume)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kubelet_volume_stats_capacity_bytes{service=\"k8s-prometheus-kubelet\"})"
    }
   ]
  },
  {
   "title": "Volume-Nutzung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\"^$namespace$\", service=\"k8s-prometheus-kubelet\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Netzwerk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Netzwerk-IO je Pod (2-Minuten-Durchschnitt)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",node=~\"^$Node$\",namespace=~\"^$namespace$\"}[2m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",node=~\"^$Node$\",namespace=~\"^$namespace$\"}[2m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "Netzwerk-IO (2-Minuten-Durchschnitt)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{node=~\"^$Node$\"}[2m]))",
     "legendFormat": "Empfangen"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{node=~\"^$Node$\"}[2m]))",
     "legendFormat": "Gesendet"
    }
   ]
  }
 ]
}